
[package]
main = "tests/main.sn"
name = "std"
version = "1.0.0"

[documentation]
entry = "./stdlib"
base = "/snowball/"

[benchmark]
entry = "./tests/main.sn"

[dependencies]
"rgb" = { version = "1.0.0" }