
[package]
main = "tests/main.sn"
name = "std"
version = "1.0.0"

[documentation]
entry = "./stdlib"
base = "/snowball/"

[benchmark]
entry = "./tests/main.sn"

[dependencies]
"mauro-balades/rgb-sn" = { version = "1.0.0" }