on:
  label:
    types:
      - created
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v3
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "14.0"
    - name: Build project
      run: |
        export CC="gcc"
        export CXX="g++"
        sh ./build_scripts/dbg.sh -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_CC_COMPILER=/usr/bin/gcc
        sudo make install
    - name: Execute fuzing bench
      run: |
          python3 tests/snowball-fuze.py
          snowball build -o O0 -s

