name: Generate documentation on push

on: [push]

jobs:
  generate_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install deps
        run: | 
            sudo apt-get install lsb-release wget software-properties-common libsigsegv-dev gnupg -y
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            sudo ./llvm.sh 16

      - name: Install snowball
        run: |
            set -x
            sh ./build_scripts/dbg.sh -j10

      - name: Execute docs
        run: |
          ./bin/Debug/snowball docgen

      - name: Copy
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: stdlib-docs
          folder: .sn/docs