name: Build and Release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, centos-latest, fedora-latest]
        cmake: [3.10, 3.11, 3.12]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v3
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "14.0"
    - name: Build project
      run: |
        sh ./build_scripts/release.sh
        make
    - name: Archive
      run: |
        mkdir release
        cp -r ./bin/Release release/
        tar -czvf snowball.tar.gz release/
    - name: Upload Release Asset
      if: success()
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./snowball.tar.gz
        asset_name: snowball.tar.gz
        asset_content_type: application/gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
