name: Build and Release
on:
  pull_request:
    branches:
      - releases
    types: [closed]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, centos-latest, fedora-latest]
        cmake: [3.10, 3.11, 3.12]
    outputs:
      version: ${{ steps.step_version.outputs.version }}
      upload_url: ${{ steps.step_upload_url.outputs.upload_url }}
      - id: step_version
        run: echo "::set-output name=version::${{ steps.package_version.outputs.version }}"
        
      - id: step_upload_url
        run: echo "::set-output name=upload_url::${{ steps.create_release.outputs.upload_url }}"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v3
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "14.0"
    - name: Build project
      run: |
        sh ./build_scripts/release.sh
        make
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ matrix.cmake }}-${{ matrix.distro }}-${{ matrix.os }}
        release_name: v${{ matrix.cmake }}-${{ matrix.distro }}-${{ matrix.os }} binaries
        draft: false
        prerelease: false
    - name: Upload binaries
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/Release
        asset_name: snowball-${{ matrix.cmake }}-${{ matrix.distro }}-${{ matrix.os }}
        asset_content_type: application/octet-stream