name: Build and Release
on:
  pull_request:
    branches:
      - releases
    types: [closed]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, centos-latest, fedora-latest]
        cmake: [3.10, 3.11, 3.12]
    steps:
    - name: "Get upload_url"
      run: echo "::set-output name=upload_url::https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets{?name,label}"
      id: release
    - uses: actions/checkout@v2
    - uses: actions/checkout@v3
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "14.0"
    - name: Build project
      run: |
        sh ./build_scripts/release.sh
        make
    - name: Archive
      run: |
        mkdir release
        cp ./bin/Release release/
        tar -czvf snowball.tar.gz release/
    - name: Create Release
      if: success()
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: This is the first release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Release Asset
      if: success()
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.build.outputs.upload_url }}
        asset_path: ./snowball.tar.gz
        asset_name: snowball.tar.gz
        asset_content_type: application/gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
