name: Test snowball
on:
  label:
    types:
      - created
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - ARCH: 'x86_64'
            DIST: 'ubuntu-20.04'
          - ARCH: 'aarch64'
            DIST: 'ubuntu-20.04'
    name: Build ${{ matrix.DIST }}  (${{ matrix.ARCH }})
    env:
      DIST: ${{ matrix.DIST }}
      ARCH: ${{ matrix.ARCH }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU integration for Docker
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build in Docker
        run: bash -ex build_scripts/release_build.sh

      - name: Test snowball
        run: # TODO: snowball test